In [1]:
import pickle

with open("benchmark=Pereira2018-encoding,model=distilgpt2,subsample=None.pkl", "rb") as f:
    content = pickle.load(f)

content

Loading lookup from /usr/local/Caskroom/miniforge/base/envs/perturbed-nnlp/lib/python3.6/site-packages/brainio_collection/lookup.csv


{'data': <xarray.Score (layer: 7, aggregation: 2)>
 array([[0.001805, 0.026412],
        [0.512346, 0.064765],
        [0.542876, 0.133199],
        [0.533012, 0.158152],
        [0.611863, 0.207171],
        [0.713166, 0.065233],
        [0.800951, 0.127054]])
 Coordinates:
   * layer        (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
   * aggregation  (aggregation) <U6 'center' 'error'
 Attributes:
     raw:          <xarray.Score (layer: 7, aggregation: 2)>\narray([[0.000575...
     ceiling:      <xarray.Score (aggregation: 3)>\narray([0.318567, 0.012958,...
     description:  ceiling-normalized score
     model:        distilgpt2
     benchmark:    Pereira2018-encoding}

In [2]:
# all_raw_scores = content["data"].raw # this gives the unceiled but aggregated language scores

In [3]:
# test_all_raw_scores = content["data"].raw.raw # this gives the unceiled, unaggregated language scores

In [4]:
all_raw_scores = content["data"].raw.raw.raw # this gives the unceiled, unaggregated scores for all atlases

In [5]:
import numpy as np
np.shape(all_raw_scores)
# 7 = layers
# 2 = experiments
# 5 = cross-val splits
# 102880 = neuroids

(7, 2, 5, 102880)

In [6]:
all_raw_scores

<xarray.Score (layer: 7, experiment: 2, split: 5, neuroid: 102880)>
array([[[[-0.193684, ...,  0.191894],
         ...,
         [-0.131249, ..., -0.01662 ]],

        [[ 0.014729, ...,  0.015859],
         ...,
         [ 0.09216 , ..., -0.065168]]],


       ...,


       [[[ 0.344274, ...,  0.165047],
         ...,
         [ 0.423848, ...,  0.304018]],

        [[ 0.285605, ...,  0.064886],
         ...,
         [ 0.251307, ...,  0.162485]]]])
Coordinates:
  * layer            (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
  * experiment       (experiment) object '243sentences' '384sentences'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 28 29 31 32 38 42 ... 152 153 154 159 160
  - filter_strategy  (neuroid) object '' '' '' '' '' '' '' ... '' '' '' '' '' ''
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroi

In [7]:
#aggregation from pipeline
from brainscore.metrics.transformations import  apply_aggregate
# https://github.com/carina-kauf/perturbed-neural-nlp/blob/master/neural_nlp/benchmarks/neural.py#L173
raw_neuroids = apply_aggregate(lambda values: values.mean('split').mean('experiment'), all_raw_scores)
raw_neuroids

/usr/local/Caskroom/miniforge/base/envs/perturbed-nnlp/lib/python3.6/site-packages/xarray/core/nanops.py:159: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis=axis, dtype=dtype)


<xarray.Score (layer: 7, neuroid: 102880)>
array([[-0.024056,  0.019942,  0.000935, ..., -0.002977, -0.041293, -0.026874],
       [ 0.188483,  0.165412,  0.209014, ...,  0.073372,  0.137351,  0.113955],
       [ 0.128264,  0.121818,  0.090112, ...,  0.113405,  0.101418,  0.104901],
       ...,
       [ 0.240067,  0.211276,  0.189139, ...,  0.189913,  0.210865,  0.217992],
       [ 0.199024,  0.215913,  0.205953, ...,  0.210164,  0.196784,  0.222444],
       [ 0.277848,  0.270639,  0.294908, ...,  0.202854,  0.224837,  0.239107]])
Coordinates:
  * layer            (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 28 29 31 32 38 42 ... 152 153 154 159 160
  - filter_strategy  (neuroid) object '' '' '' '' '' '' '' ... '' '' '' '' '' ''
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi         

In [8]:
# #old with Greta
# avg_scores_over_folds = all_raw_scores.mean(axis=2)
# avg_scores_over_folds

In [9]:
language_neuroids = raw_neuroids.sel(atlas='language', _apply_raw=False)
language_neuroids

<xarray.Score (layer: 7, neuroid: 13517)>
array([[-0.024056,  0.019942,  0.000935, ...,  0.015881,  0.014986,  0.024248],
       [ 0.188483,  0.165412,  0.209014, ...,  0.094655,  0.099072,  0.186072],
       [ 0.128264,  0.121818,  0.090112, ...,  0.112316,  0.118214,  0.171203],
       ...,
       [ 0.240067,  0.211276,  0.189139, ...,  0.154961,  0.125806,  0.323611],
       [ 0.199024,  0.215913,  0.205953, ...,  0.210484,  0.203453,  0.389707],
       [ 0.277848,  0.270639,  0.294908, ...,  0.238168,  0.223364,  0.35344 ]])
Coordinates:
  * layer            (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 28 29 31 32 38 42 ... 152 153 154 159 160
  - filter_strategy  (neuroid) object '' '' '' '' '' '' '' ... '' '' '' '' '' ''
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi          

In [10]:
# import xarray
# xarray.DataArray.equals(test_all_raw_scores, language_neuroids)
# >> True

# Get MD scores

In [11]:
md_neuroids = raw_neuroids.sel(atlas='MD', _apply_raw=False)
md_neuroids

<xarray.Score (layer: 7, neuroid: 29845)>
array([[ 0.008169, -0.018107,  0.018264, ..., -0.002977, -0.041293, -0.026874],
       [ 0.138259,  0.101357,  0.155139, ...,  0.073372,  0.137351,  0.113955],
       [ 0.162599,  0.157011,  0.192888, ...,  0.113405,  0.101418,  0.104901],
       ...,
       [ 0.221473,  0.195824,  0.230805, ...,  0.189913,  0.210865,  0.217992],
       [ 0.307069,  0.229747,  0.243876, ...,  0.210164,  0.196784,  0.222444],
       [ 0.267572,  0.248221,  0.267752, ...,  0.202854,  0.224837,  0.239107]])
Coordinates:
  * layer            (layer) object 'drop' 'encoder.h.0' ... 'encoder.h.5'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 3159 3160 3161 3175 ... 3833 3834 3844 3845
  - filter_strategy  (neuroid) object 'HminusE' 'HminusE' ... 'HminusE'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (ne

In [12]:
layers = list(md_neuroids.layer.data)
layers

['drop',
 'encoder.h.0',
 'encoder.h.1',
 'encoder.h.2',
 'encoder.h.3',
 'encoder.h.4',
 'encoder.h.5']

In [13]:
test = md_neuroids.sel(layer='drop')
test

<xarray.Score (neuroid: 29845)>
array([ 0.008169, -0.018107,  0.018264, ..., -0.002977, -0.041293, -0.026874])
Coordinates:
    layer            <U4 'drop'
  * neuroid          (neuroid) MultiIndex
  - subject          (neuroid) object '018' '018' '018' ... '018' '018' '018'
  - voxel_num        (neuroid) int64 3159 3160 3161 3175 ... 3833 3834 3844 3845
  - filter_strategy  (neuroid) object 'HminusE' 'HminusE' ... 'HminusE'
  - atlas_selection  (neuroid) object 'from90to100prcnt' ... 'from90to100prcnt'
  - roi              (neuroid) object 'LH_insula' 'LH_insula' ... 'LH_insula'
  - indices_in_3d    (neuroid) int64 170304 170305 170306 ... 178200 178201
  - col_to_coord_1   (neuroid) int64 59 60 61 59 56 55 56 ... 56 54 55 56 55 56
  - col_to_coord_2   (neuroid) int64 66 66 66 67 68 69 69 ... 69 70 70 70 71 71
  - col_to_coord_3   (neuroid) int64 23 23 23 23 23 23 23 ... 24 24 24 24 24 24
  - neuroid_id       (neuroid) object '018.3159' '018.3160' ... '018.3845'
Attributes:
    raw:  

In [14]:
from brainio_base.assemblies import DataAssembly, merge_data_arrays
from brainscore.metrics import Score

In [15]:
from scipy.stats import median_absolute_deviation

def aggregate_neuroid_scores(neuroid_scores, subject_column):
    subject_scores = neuroid_scores.groupby(subject_column).median()
    center = subject_scores.median(subject_column)
    subject_values = np.nan_to_num(subject_scores.values, nan=0)  # mad cannot deal with all-nan in one axis, treat as 0
    subject_axis = subject_scores.dims.index(subject_scores[subject_column].dims[0])
    error = median_absolute_deviation(subject_values, axis=subject_axis)
    score = Score([center, error], coords={'aggregation': ['center', 'error']}, dims=['aggregation'])
    score.attrs['raw'] = neuroid_scores
    score.attrs['description'] = "score aggregated by taking median of neuroids per subject, " \
                                 "then median of subject scores"
    return score

In [16]:
for layer in layers:
    md_neuroids.sel(layer=layer)
    score = aggregate_neuroid_scores(md_neuroids.sel(layer=layer), "subject")
    print(f"{layer} | Score: {score.data}")

drop | Score: [0.00585957 0.02262233]
encoder.h.0 | Score: [0.12298596 0.03137098]
encoder.h.1 | Score: [0.14446792 0.01864211]
encoder.h.2 | Score: [0.1392752  0.02350483]
encoder.h.3 | Score: [0.17672698 0.02005617]
encoder.h.4 | Score: [0.20776767 0.03274536]
encoder.h.5 | Score: [0.23402109 0.01722397]


In [17]:
# #old with Greta
# grouped = md_neuroids.groupby("subject").median()
# grouped
# final_score = grouped.median()
# final_score.item()
# final_score = grouped.median()
# final_score.item()
# >> 0.1572379546863542